### ISSUE TITLE
مشکل عدم نمایش اطلاعات

### ISSUE THREAD

**Issue by ArminDelavari** [TeleDark/v2ray-tel-bot#35]
سلام روزتون بخیر ممنون برای این افزونه 
من افزونه رو عین فیلم آموزشی اضافه کردم و دستور چک کردن اتصال رو هم می زنم قشنگ متصل میشه فقط نمی دونم چرا هر کدوم از اون اطلاعات رو که می زنم می نویسه 

"اطلاعات اکانت شما پیدا نشد! "

مشکل از چی هستش ؟ می تونین راهنمایی کنین ؟

**Comment by TeleDark** [comment]
لطفا عضو چنل بشید و سوالتون رو داخل بخش گفتگو بپرسید
و از دستور python3 login.py اسکرین بزارید

**Comment by aradesign** [comment]
با همه پنلا همخونی داره؟
من با پنل مرزبان خواستم تست کنم بعد از اجرای دستور لاگین، این خطا رو میده:
Traceback (most recent call last):
  File "/root/v2ray-tel-bot/login.py", line 5, in <module>
    from keys import *
  File "/root/v2ray-tel-bot/keys.py", line 12, in <module>
    config_yaml = yaml.safe_load(f)
  File "/usr/local/lib/python3.10/dist-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.10/dist-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.10/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/local/lib/python3.10/dist-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/usr/local/lib/python3.10/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.10/dist-packages/yaml/parser.py", line 392, in parse_block_sequence_entry
    raise ParserError("while parsing a block collection", self.marks[-1],
yaml.parser.ParserError: while parsing a block collection
  in "/root/v2ray-tel-bot/config/config.yml", line 4, column 3
expected <block end>, but found '<block sequence start>'
  in "/root/v2ray-tel-bot/config/config.yml", line 8, column 4
  

میشه یه توضیح درخصوص پنل اجراش با مرزبان هم بدین؟

**Comment by TeleDark** [comment]
متاسفانه با پنل مرزبان همخوانی نداره برنامه
